### ISSUE TITLE
Data for the Lorenz example

### ISSUE THREAD

**Issue by masterdezign** [zabaras/transformer-physx#1]
Hello!

Thank you for the interesting paper.

Could you please share the data you used for the Lorenz benchmark?

Thank you

**Comment by NickGeneva** [comment]
All data uploaded on Zenodo data repo as of commit 9b9341bc0dccbe9078847aa32d6cfe54e78ecf3a. See readme for link.

Google Collab notebooks will also download data into your Google drive.
